"""
Agent Factory — AgentLog ORM Model.

Persists every agent task execution to PostgreSQL for audit,
dashboard display, and long-term analytics.

Redis (Paperclip) handles real-time / short-lived logs (TTL 24h).
This table handles permanent, queryable history.

Table: agent_logs
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Float, Index, String, Text, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class AgentLog(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Immutable record of a single agent task execution.

    Written by the API layer after Paperclip.dispatch() returns.
    Never updated — append-only audit log.
    """

    __tablename__ = "agent_logs"

    # ── Task identity ──────────────────────────────────────────────────────────
    task_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        unique=True,
        index=True,
        comment="UUID generated by Paperclip per dispatch call",
    )

    # ── Agent routing ──────────────────────────────────────────────────────────
    agent_name: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="Class name of the agent that handled this task",
    )
    domain: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        index=True,
        comment="leave | payroll | attendance | chatbot",
    )
    action: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        comment="Domain-specific action key (e.g. analyse, validate, daily_report)",
    )

    # ── Execution outcome ──────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        index=True,
        comment="success | error | skipped",
    )
    result: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Full agent result payload (recommendation, anomalies, summary, etc.)",
    )
    duration_ms: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="End-to-end task duration in milliseconds",
    )

    # ── Context ───────────────────────────────────────────────────────────────
    tenant_id: Mapped[str | None] = mapped_column(
        String(64),
        nullable=True,
        index=True,
        comment="Tenant slug or UUID; NULL for cross-tenant scheduled tasks",
    )
    triggered_by: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="api",
        comment="scheduler | webhook | api_trigger | manual",
    )
    triggered_by_user_id: Mapped[str | None] = mapped_column(
        String(36),
        nullable=True,
        comment="User UUID if triggered via API; NULL for automated triggers",
    )

    # ── AI model metadata ──────────────────────────────────────────────────────
    model_used: Mapped[str | None] = mapped_column(
        String(64),
        nullable=True,
        comment="Claude model ID used (e.g. claude-sonnet-4-6) or 'mock' / 'rule-based'",
    )
    input_tokens: Mapped[int | None] = mapped_column(
        nullable=True,
        comment="Claude API input token count (for cost tracking)",
    )
    output_tokens: Mapped[int | None] = mapped_column(
        nullable=True,
        comment="Claude API output token count (for cost tracking)",
    )

    # ── Composite indexes ──────────────────────────────────────────────────────
    __table_args__ = (
        Index("ix_agent_logs_domain_action",   "domain", "action"),
        Index("ix_agent_logs_tenant_created",  "tenant_id", "created_at"),
        Index("ix_agent_logs_status_created",  "status",    "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<AgentLog task_id={self.task_id!r} domain={self.domain!r} "
            f"action={self.action!r} status={self.status!r}>"
        )

    def to_dict(self) -> dict:
        return {
            "id":                   str(self.id),
            "task_id":              self.task_id,
            "agent_name":           self.agent_name,
            "domain":               self.domain,
            "action":               self.action,
            "status":               self.status,
            "result":               self.result,
            "duration_ms":          self.duration_ms,
            "tenant_id":            self.tenant_id,
            "triggered_by":         self.triggered_by,
            "triggered_by_user_id": self.triggered_by_user_id,
            "model_used":           self.model_used,
            "input_tokens":         self.input_tokens,
            "output_tokens":        self.output_tokens,
            "created_at":           self.created_at.isoformat() if self.created_at else None,
        }
